import { Helmet } from "react-helmet-async";
import { globalMetadata } from "@/data/seo";

interface SEOProps {
  title: string;
  description: string;
  keywords?: string;
  image?: string;
  url?: string;
  type?: string;
  jsonLd?: Record<string, any>;
  additionalSchemas?: Record<string, any>[]; // Support multiple schemas
  noIndex?: boolean;
}

const SEO = ({
  title,
  description,
  keywords = globalMetadata.organizationSchema.description, // Fallback if needed, though keywords usually specific
  image = Array.isArray(globalMetadata.organizationSchema.image) 
    ? globalMetadata.organizationSchema.image[0] 
    : globalMetadata.organizationSchema.image,
  url = globalMetadata.organizationSchema.url,
  type = "website",
  jsonLd,
  additionalSchemas = [],
  noIndex = false,
}: SEOProps) => {
  const siteTitle = globalMetadata.siteName;
  // If the title already contains the site name or is the site name, use it as is, otherwise append
  const fullTitle = title === siteTitle || title.includes(siteTitle) ? title : `${title} | ${siteTitle}`;
  const fullUrl = url.startsWith("http")
    ? url
    : `https://food.9yards.co.ug${url}`;
  const fullImage = image.startsWith("http")
    ? image
    : `https://food.9yards.co.ug${image}`;

  // Generate Breadcrumb Schema
  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://food.9yards.co.ug"
      },
      ...(url !== "/" && url !== "https://food.9yards.co.ug/" ? [{
        "@type": "ListItem",
        "position": 2,
        "name": title.split("|")[0].trim().substring(0, 30), // Simple name extraction
        "item": fullUrl
      }] : [])
    ]
  };

  // Default Schema.org Structured Data
  // We use the global organization schema as a base for defaults or generic pages
  const defaultStructuredData = {
    ...globalMetadata.organizationSchema,
    image: [fullImage],
    description: description,
    url: fullUrl,
  };

  const finalStructuredData = jsonLd ? { ...defaultStructuredData, ...jsonLd } : defaultStructuredData;

  const aiMeta = globalMetadata.aiMetadata;

  return (
    <Helmet>
      {/* Basic Meta Tags */}
      <title>{fullTitle}</title>
      <meta name="description" content={description} />
      <meta name="keywords" content={keywords} />
      {noIndex ? (
        <meta name="robots" content="noindex, nofollow" />
      ) : (
        <meta name="robots" content={aiMeta.robots} />
      )}
      <meta name="messages" content="AI-crawler-friendly" />
      
      {/* Site Verification */}
      <meta name="google-site-verification" content={globalMetadata.verification.google} />

      {/* AI & Crawler Specific */}
      <meta name="googlebot" content={aiMeta.googlebot} />
      <meta name="bingbot" content={aiMeta.bingbot} />
      <meta name="author" content={aiMeta.author} />
      <meta name="generator" content={aiMeta.generator} />
      <meta name="citation_publisher" content={aiMeta.citation_publisher} />
      <meta name="citation_online_date" content={aiMeta.citation_online_date} />

      <link rel="canonical" href={fullUrl} />
      
      {/* Favicon for all pages - Generated by realfavicongenerator.net */}
      <link rel="icon" type="image/png" sizes="96x96" href="/images/logo/favicon-96x96.png" />
      <link rel="icon" type="image/svg+xml" href="/images/logo/favicon.svg" />
      <link rel="icon" type="image/x-icon" href="/images/logo/favicon.ico" />
      <link rel="shortcut icon" href="/images/logo/favicon.ico" />
      <link rel="apple-touch-icon" sizes="180x180" href="/images/logo/apple-touch-icon.png" />

      {/* Open Graph / Facebook */}
      <meta property="og:type" content={type} />
      <meta property="og:url" content={fullUrl} />
      <meta property="og:title" content={fullTitle} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={fullImage} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:alt" content={`${title} - 9Yards Food`} />
      <meta property="og:site_name" content={siteTitle} />
      <meta property="og:locale" content={globalMetadata.locale} />

      {/* Hreflang for international SEO */}
      <link rel="alternate" hrefLang="en-ug" href={fullUrl} />
      <link rel="alternate" hrefLang="x-default" href={fullUrl} />

      {/* Twitter */}
      <meta name="twitter:card" content={globalMetadata.twitterCard} />
      <meta name="twitter:site" content={globalMetadata.twitterSite} />
      <meta name="twitter:url" content={fullUrl} />
      <meta name="twitter:title" content={fullTitle} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={fullImage} />
      <meta name="twitter:image:alt" content={`${title} - 9Yards Food`} />

      {/* Structured Data: Organization/Page */}
      <script type="application/ld+json">
        {JSON.stringify(finalStructuredData)}
      </script>

      {/* Structured Data: WebSite - For Brand Search & Sitelinks */}
      <script type="application/ld+json">
        {JSON.stringify(globalMetadata.websiteSchema)}
      </script>

      {/* Structured Data: Breadcrumbs */}
      <script type="application/ld+json">
        {JSON.stringify(breadcrumbSchema)}
      </script>

      {/* Additional Structured Data (FAQ, etc.) */}
      {additionalSchemas.map((schema, index) => (
        <script key={index} type="application/ld+json">
          {JSON.stringify(schema)}
        </script>
      ))}
    </Helmet>
  );
};

export default SEO;
